POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstname" :  "Bob",
  "email" : "q@q",
  "password" :  "123"
}

> {% client.global.set("authToken", response.body.access_token); %}

###
POST http://localhost:8080/api/auth/refresh-token
Authorization: Bearer {{authToken}}
Content-Type: application/json


