spring:
  datasource:
    url: ${POSTGRES_URL}
    username: postgres
    password: ${POSTGRES_PW}  # this is for local application only
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: ${MONGO_URL}
      database: DeleteMeDb

  hibernate:
    ogm:
      datastore:
        provider: MONGODB
        database: DeleteMeDb
        host: localhost
        username: ${MONGO_USER}
        password: ${MONGO_PASSWORD}
      create_database: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days